In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import holidays

ventas = pd.read_csv("../data/raw/entrenamiento/ventas.csv")
competencia = pd.read_csv("../data/raw/entrenamiento/competencia.csv")

In [2]:
ventas.head()

,fecha,producto_id,nombre,categoria,subcategoria,precio_base,es_estrella,unidades_vendidas,precio_venta,ingresos
0,2021-10-25,PROD_001,Nike Air Zoom Pegasus 40,Running,Zapatillas Running,115,True,6,118.36,710.16
1,2021-10-25,PROD_002,Adidas Ultraboost 23,Running,Zapatillas Running,135,True,10,136.82,1368.20
2,2021-10-25,PROD_003,Asics Gel Nimbus 25,Running,Zapatillas Running,85,False,2,84.93,169.86
3,2021-10-25,PROD_004,New Balance Fresh Foam X 1080v12,Running,Zapatillas Running,75,False,2,75.42,150.84
4,2021-10-25,PROD_005,Nike Dri-FIT Miler,Running,Ropa Running,35,False,2,35.87,71.74

In [3]:
competencia.head()

        fecha producto_id  Amazon  Decathlon  Deporvillage
0  2021-10-25    PROD_001   82.96     111.88         97.43
1  2021-10-25    PROD_002  112.56     108.61        115.58
2  2021-10-25    PROD_003   79.79      78.44         80.11
3  2021-10-25    PROD_004   72.60      67.29         74.45
4  2021-10-25    PROD_005   37.71      33.60         33.07